In [1]:
import pandas as pd
import os

In [2]:
directory = '../data/2016_chunks/'
all_dfs = []  
for filename in os.listdir(directory):
    print(filename)
    df = pd.read_csv(directory+filename, low_memory=True)
    all_dfs.append(df)

2016_0_of_22.csv

c:\Users\saich\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (19,21) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

2016_10_of_22.csv
2016_11_of_22.csv
2016_12_of_22.csv
2016_13_of_22.csv
2016_14_of_22.csv
2016_15_of_22.csv
2016_16_of_22.csv
2016_17_of_22.csv
2016_18_of_22.csv
2016_19_of_22.csv
2016_1_of_22.csv
2016_20_of_22.csv
2016_21_of_22.csv
2016_2_of_22.csv
2016_3_of_22.csv
2016_4_of_22.csv
2016_5_of_22.csv
2016_6_of_22.csv
2016_7_of_22.csv
2016_8_of_22.csv
2016_9_of_22.csv

In [3]:
final_df = pd.concat(all_dfs)
final_df.to_csv('2016_final.csv', index=False)

In [4]:
final_df

,census_tract,parcelid,airconditioningtypeid,bathroomcnt,bedroomcnt,buildingqualitytypeid,calculatedbathnbr,calculatedfinishedsquarefeet,finishedsquarefeet12,fips,...,landtaxvaluedollarcnt,taxamount,censustractandblock,state,total,hispanic_or_latino,not_hispanic_or_latino,white_alone,black_alone,asian_alone
0,603743200,13006323,1.0,5.0,4.0,4.0,5.0,3314.0,3314.0,6037,...,375669.0,8444.98,6.037432e+13,6,NaN,NaN,NaN,NaN,NaN,NaN
1,6037101110,11002180,NaN,1.0,3.0,7.0,1.0,1376.0,1376.0,6037,...,170006.0,3549.59,6.037101e+13,6,4926.0,1381.0,3545.0,2840.0,65.0,434.0
2,6037101110,11002287,NaN,1.0,2.0,7.0,1.0,824.0,824.0,6037,...,55705.0,2046.57,6.037101e+13,6,4926.0,1381.0,3545.0,2840.0,65.0,434.0
3,6037101110,11002027,NaN,0.0,0.0,NaN,NaN,NaN,NaN,6037,...,153600.0,5340.18,6.037101e+13,6,4926.0,1381.0,3545.0,2840.0,65.0,434.0
4,6037101110,10996836,NaN,1.0,2.0,7.0,1.0,720.0,720.0,6037,...,181534.0,2880.69,6.037101e+13,6,4926.0,1381.0,3545.0,2840.0,65.0,434.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,6111009100,17162527,NaN,2.0,4.0,NaN,2.0,1255.0,1255.0,6111,...,9124.0,441.14,6.111009e+13,6,6270.0,5482.0,788.0,338.0,137.0,174.0
99996,6111009100,17162039,NaN,1.0,4.0,NaN,1.0,1588.0,1588.0,6111,...,112705.0,3377.74,6.111009e+13,6,6270.0,5482.0,788.0,338.0,137.0,174.0
99997,6111009100,17162018,NaN,1.0,3.0,NaN,1.0,1041.0,1041.0,6111,...,186054.0,3096.96,6.111009e+13,6,6270.0,5482.0,788.0,338.0,137.0,174.0
99998,6111009100,17162384,NaN,1.0,4.0,NaN,1.0,1080.0,1080.0,6111,...,115992.0,2851.06,6.111009e+13,6,6270.0,5482.0,788.0,338.0,137.0,174.0
99999,6111009100,17162484,NaN,2.0,3.0,NaN,2.0,1044.0,1044.0,6111,...,134000.0,3238.92,6.111009e+13,6,6270.0,5482.0,788.0,338.0,137.0,174.0

In [ ]:
directory = '../data/2017_chunks/'
all_dfs = []  
for filename in os.listdir(directory):
    df = pd.read_csv(directory+filename, low_memory=True)
    all_dfs.append(df)
    
final_df = pd.concat(all_dfs)
final_df.to_csv('../data/2017_final.csv', index=False)